{-------------------------------------------------------------------------------
  Configuration file for the DuGet project.
  Comment the definition of GNUGETTEXT if you don't want use the gnugettext
  of JEDI.
  If you comment the definition of GNUGETTEXT, the unit DuGet.Translator will
  be used. In that unit, you have to implement your system for translations.
-------------------------------------------------------------------------------}
{$DEFINE GNUGETTEXT}